# Generated by Django 4.2.7 on 2023-12-04 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_alter_customuser_managers_alter_invigilator_managers_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invigilator",
            options={
                "verbose_name": "Invigilator",
                "verbose_name_plural": "Invigilators",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
    ]
